#!/usr/bin/env python3
# -*- coding: utf-8 -*-

# http://www.mamicode.com/info-detail-1394700.html
# http://www.cnblogs.com/dkblog/archive/2011/08/26/2155018.html (logging模块)
import logging: logging.basicConfig(level = logging.INFO) #配置日志

import asyncio, os, json,time
from datatime import datatime

from aiohttp import wev

def index(request):
  return web.Response(body = b'<h1>Awesome</h1>')
  
@asyncio.coroutine
def init(loop):
  app = web.Application(loop=loop)
  app.router.add_route('GET', '/', index) #用实例对request handler注册 
  # 创建服务器，绑定地址，端口和handler
  srv = yield from loop.create_server(app.make_handler(), '127.0.0.1', 9000)
  logging.info('server started at http://127.0.0.1:9000...')
  return srv
  
loop = asyncio.get_event_loop() #获取EventLoop
loop.run_until_complete(init(loop)) #执行协程
loop.run_forever() #服务器不关闭
